export default [
  ['element-animation-lottie', `
    <element-animation-lottie autoplay loop src="node_modules/@damienmortini/element-animation-lottie/demo/data.json"></element-animation-lottie>
  `],
  // 'element-animation-sprite',
  // 'element-animation-ticker',
  // 'element-gl-image',
  // 'element-gl-video',
  'element-input-button',
  'element-input-checkbox',
  'element-input-color',
  'element-input-colorpicker',
  // 'element-input-connector',
  // 'element-input-connector-linkable',
  // 'element-input-file',
  // 'element-input-joystick',
  // 'element-input-number',
  // 'element-input-pad2d',
  // 'element-input-range',
  // 'element-input-select',
  // 'element-input-soundmatrix',
  // 'element-input-text',
  // 'element-link',
  // 'element-menu',
  // 'element-video-gl',
  // 'element-view',
  // 'element-viewport',
  // 'element-zoomable',
];

